name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
       with:
    # User defined upload name. Visible in Codecov UI
    name: # optional
    # Repository upload token - get it from codecov.io
    token: 7629f033-dbdc-4d3a-849e-882aae30fe41
